### ISSUE TITLE
Potential job opportunity

### ISSUE THREAD

**Issue by LoiLock** [Markiesch/EpicPunishments#11]
Hey, I really would've preferred to do this over email. But basically, we're looking for a frontend developer in Den Bosch. We're close to kw1c, just got a new office, and are extremely interested in your skills. Personally, I like your code style a lot, and I can guarantee that we can provide you with a really cool work environment where you can continue to develop your abilities further.
I saw that you already have an internship in Den Bosch, but again, I guarantee that we can offer a place where you truly get to develop your skills further.

If you're interested, you can reach me on either of these emails (or just reply here, either way I'll see it):
jochem.hagenaars@gmail.com
jochem@metalface.com

**Comment by markschuurmans** [comment]
Hey @LoiLock thanks for your message, I have send my response via email
